name: X Auto Like

on:
  schedule:
    - cron: "15 0 * * *"  # ✅ 日本時間の午前9:15に実行（UTCで0:15）
  workflow_dispatch:

jobs:
  like_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install tweepy

    - name: Run script
      run: python like.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }} 
