name: Auto Reply Bot

on:
  schedule:
    - cron: "30 0 * * *"  # 毎日9:30 JST（UTC 0:30）
  workflow_dispatch:

jobs:
  reply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install tweepy openai python-dotenv

      - name: Run reply bot
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
        run: python reply_bot.py
